 # Config File
 # BetterThings 1.0
 # By Ask Gaming(Amonly)
  
  
task: 1200 # In ticks: 20ticks = 1s
  
thirst: # Max 200
  task: 1200 # How often the plugin will check your thirst and increase it 
  howmuch: 6 # How much thirst will be increased in the task time
  50:
    msg: '&bIm a little thirsty..'
  100:
    msg: '&bIm so thirsty..'
  150:
    msg: '&bIm dying of thirst'


fatigue: # Max 250
  task: 1200 # How often the plugin will check your fatigue and increase it 
  howmuch: 4 # How much fatigue will be increased in the task time
  100:
    msg: '&cIm a little sleepy..'
  150:
    msg: '&cI am very sleepy.. but I can continue!'
  200:
    msg: '&cI am very tired, I should sleep..'
    
messages:
  tootired: '&cI am too tired to do that, I should sleep first.'
  tiredtorun: '&cI am too tired to run..'
  regenthirst: '&cYou will not regenerate life with such thirst'
  regenfatigue: '&cYou wont regenerate life when you are so tired'
  restinday: '&2I have not slept but I have rested something'
  aftersleep: '&2Mhh, sleeping has made me a little hungry..'
  #
  ongivethirst: '&2You gave full thirst to '
  ongivefatigue: '&2You gave full fatigue to '
  onrefreshthirst: '&2You refresh thirst of '
  onrefreshfatigue: '&2You refresh fatigue of '
  onthirstchange: '&2Your thirst has been changed.'
  onfatiguechange: '&2You Fatigue has been changed.'
  help:
  - ''
  - '&7>> &7BetterThings Help Menu'
  - '&7>> &3/thirst'
  - '&7>> &3/fatigue'
  - ''
  - '&7>> &6/betterthings &fmaxthirst'
  - '&7>> &6/betterthings &frefreshthirst'
  - '&7>> &6/betterthings &fmaxfatigue'
  - '&7>> &6/betterthings &frefreshfatigue'
  - ''
  - '&7>> &6/betterthings &7coffe, wine, lemonade, juice, godjuice, milk'
  - ''

# For now you only can change the name and the lore of the new drinks
# It will be more custom in the future

items:
  coffename: '&6Coffe'
  coffelore:
  - ''
  - '&7Thirst: &b-25'
  - '&7Fatigue: &c-25'  
  
  milkname: '&fMilk'
  milklore:
  - ''
  - '&7Thirst: &b-60'
  
  winename: '&5Wine'
  winelore:
  - ''
  - '&7Thirst: &b-40' 
  
  lemonadename: '&aLemonade'
  lemonadelore:
  - ''
  - '&7Thirst: &b-70'
  
  juicename: '&cApple Juice'
  juicelore:
  - ''
  - '&7Thirst: &b-60' 
  
  godjuicename: '&eGod Juice'
  godjuicelore:
  - ''
  - '&bQuench thirst'
  - '&cTake away the fatigue'
  - '&6Absorption!' 
 
 
# This materials will be bypassed to place when you are too tired
materials:
- WHITE_BED
- RED_BED
- ORANGE_BED
- BLACK_BED
- MAGENTA_BED
- LIGHT_BLUE_BED
- BLUE_BED
- YELLOW_BED
- GREEN_BED
- PINK_BED
- GRAY_BED
- LIGHT_GRAY_BED
- CYAN_BED
- PURPLE_BED
- BROWN_BED
- LIME_BED