main: betterthings.Main
name: Betterthings
version: 1.0
author: AMONLY
api-version: 1.15
website: web.askgaming.org
commands:
  thirst:
    description: Show your thirst.
  fatigue:
    description: Show your fatigue.
  betterthings:
    description: Help Menu.
