# Config File - BetterThings - By Ask Gaming(Amonly)
# If you need help, please contact me on Discord: 

#If you disble constant_action_bar, the plugin will send a message every time the player changues the value of thirst or fatigue
#If you disable_action_bar, the plugin will not send any action bar to the player
#Decay percentage of the lemon item, 0.1 = 10% of decay - #Apple has 0.05 of decay
constant_action_bar: true
disable_action_bar: false

thirst: 
  emoji: 🍶
  decrease: 0.25 # Amount of decrease in the thirst value every 60 seconds
  max_value: 20.0
  increase_on_fire_blocks: true
  cancel_regain_health_below: 4.0
  enable_worlds:
  - world
  - world_nether
  values:
    15:
      message: "&eYou start to feel a little thirsty."
      damage: 0
      commands: []
      effects: []
      sounds: []
    10:
      message: "&cYour mouth feels dry."
      damage: 0
      commands: []
      effects:
        - WEAKNESS:60:0
      sounds: 
        - ENTITY_PLAYER_BURP
    7:
      message: "&cYour throat is dry, you need water."
      damage: 0
      commands: []
      effects:
        - MINING_FATIGUE:60:0
        - WEAKNESS:60:0
      sounds: 
        - ENTITY_PLAYER_HURT
    5:
      message: "&4Your throat is dry, you need water."
      damage: 0
      commands: []
      effects:
        - SLOWNESS:120:1
        - MINING_FATIGUE:120:1
      sounds: 
        - ENTITY_ZOMBIE_AMBIENT
    3:
      message: "&4You feel extremely dehydrated, you can barely stand."
      damage: 0
      commands: []
      effects:
        - NAUSEA:60:0
        - WEAKNESS:120:1
        - HUNGER:120:1
      sounds: 
        - ENTITY_ENDERMAN_SCREAM
    1:
      message: "&4¡Your body can't handle any more dehydration!"
      damage: 1
      commands: []
      effects:
        - WEAKNESS:300:2
        - SLOWNESS:300:2
        - NAUSEA:300:1
      sounds:
        - ENTITY_WITHER_AMBIENT

    0:
      message: "&4¡You collapse from dehydration!"
      damage: 2
      commands:
        #- "kill %player%"
      effects:
        - WEAKNESS:600:3
        - NAUSEA:600:2
        - SLOWNESS:600:3
      sounds:
        - ENTITY_WARDEN_ROAR

fatigue:
  emoji: 🛌
  decrease: 0.25 # Amount of decrease in the fatigue value every 60 seconds
  max_value: 20.0
  force_sleep_in_day: true
  hunger_after_sleep: true
  rest_inday_increase: 5.0
  cancel_regain_health_below: 4.0
  cancel_sprint_below: 5.0
  cancel_swim_below: 5.0
  enable_worlds:
  - world
  - world_the_end
  values: # This actions will be executed when the player reaches this exact value
    15:
      message: "&eYour energy starts to drop."
      damage: 0
      commands: []
      effects:
        - HASTE:60:0
      sounds: []
    10:
      message: "&cYou feel a little tired."
      damage: 0
      commands: []
      effects:
        - MINING_FATIGUE:60:0
      sounds: 
        - ENTITY_PLAYER_BURP
    7:
      message: "&cYour body feels heavier."
      damage: 0
      commands: []
      effects:
        - SLOWNESS:60:0
      sounds: 
        - ENTITY_PLAYER_HURT
    5:
      message: "&4You are very sleepy, it is difficult for you to move."
      damage: 0
      commands: []
      effects:
        - MINING_FATIGUE:120:1
        - SLOWNESS:120:1
      sounds: 
        - ENTITY_ZOMBIE_AMBIENT
    3:
      message: "&4You feel extremely exhausted, you can hardly stand."
      damage: 0
      commands: []
      effects:
        - BLINDNESS:30:0
        - WEAKNESS:120:1
        - MINING_FATIGUE:120:1
      sounds: 
        - ENTITY_ENDERMAN_SCREAM
    1:
      message: "&4¡Your body collapses from exhaustion!"
      damage: 1
      commands: []
      effects:
        - NAUSEA:100:1
        - BLINDNESS:60:0
        - SLOWNESS:120:2
        - MINING_FATIGUE:120:2
      sounds:
        - ENTITY_WITHER_AMBIENT
    0:
      message: "&4¡You fainted from exhaustion!"
      damage: 2
      commands: []
      effects:
        - WEAKNESS:300:2
        - NAUSEA:300:2
        - SLOWNESS:600:3
        - BLINDNESS:600:1
        - MINING_FATIGUE:600:3
      sounds:
        - ENTITY_WARDEN_ROAR

others:
  enable_recipes: true
  lemon_item_name: "&aLemon"
  chance_decay_drop: 0.1

drink_from_water_block: #Drink from water block
  enable: true
  value: 10 #10 thirst value
  chance_to_get_sick: 30 #30%
