# Config File - BetterThings - By Ask Gaming(Amonly)
# If you need help, please contact me on Discord: 

#Thirst max: 200 - Fatigue max: 250 - The decrease task is per minute
#If you disble constant_action_bar, the plugin will send a message every time the player changues the value of thirst or fatigue
#Decay percentage of the lemon item, 0.1 = 10% of decay - #Apple has 0.05 of decay
constant_action_bar: true

thirst: 
  emoji: 🍶
  decrease: 4 
  amount_on_fire_blocks: true
  damage_when_0: 1
  deny_actions:
    regain_health_below: 25
    nausea_on_place_blocks_below: 50
  deny_actions:
    
  enable_worlds:
  - world
  - world_nether
     
fatigue: 
  emoji: 🛌
  decrease: 2 
  rest_inday_increase: 50
  force_sleep_in_day: true
  hunger_after_sleep: true
  damage_when_0: 1
  deny_actions:
    regain_health_below: 25
    cancel_sprint_below: 50
    minig_fatigue_below: 70
  enable_worlds:
  - world
  - world_the_end

others:
  enable_recipes: true
  lemon_item_name: "&aLemon"
  chance_decay_drop: 0.1