main: com.ar.askgaming.betterthings.Main
name: BetterThings
version: 2.1
author: AMONLY
api-version: 1.16
softdepend: [Essentials, CMI, PlaceholderAPI, Vault]
commands:
  bar: 
    description: Open the shop.
  thirst:
    aliases: [sed]
    description: Show your thirst.
  fatigue:
    aliases: [cansancio]
    description: Show your fatigue.
  betterthings:
    description: Help Menu.
