main: com.ar.askgaming.betterthings.BetterThings
name: BetterThings
version: 2.5.1
author: AMONLY
api-version: 1.21
softdepend: [Essentials, CMI, PlaceholderAPI, Vault]
commands:
  bar: 
    description: Open the shop.
    permission: betterthings.bar
  thirst:
    aliases: [sed]
    description: Show your thirst.
    permission: betterthings.thirst
  fatigue:
    aliases: [cansancio]
    description: Show your fatigue.
    permission: betterthings.fatigue
  betterthings:
    aliases: [bt]
    description: Help Menu.
    permission: betterthings.admin
